### ISSUE TITLE
Unsupported tailwind class 

### ISSUE THREAD

**Issue by edw19** [vadimdemedes/tailwind-rn#128]
![image](https://user-images.githubusercontent.com/47750859/149855893-a75e854f-28ca-4976-abfa-a6ed14aee408.png)

I am starting to use tailwind-rn in my project and I have this warning I followed the installation guide but it did not work

**Comment by Vann-Dev** [comment]
> ![image](https://user-images.githubusercontent.com/47750859/149855893-a75e854f-28ca-4976-abfa-a6ed14aee408.png)
> 
> I am starting to use tailwind-rn in my project and I have this warning I followed the installation guide but it did not work

#124

**Comment by khaladj** [comment]
Same issue here.

**Comment by vyrru5** [comment]
Got issue when I run  'npm run build:tailwind'

Error: Failed to parse declaration "transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))"

**Comment by mjrdnk** [comment]
Looks like this is related https://github.com/vadimdemedes/tailwind-rn/issues/130.

**Comment by jonsamp** [comment]
I ran into multiple issues when setting up this package in a new Expo project:

1. I needed to install the postcss library to allow the `npx setup-tailwind-rn` to run successfully.
2. My **tailwind.css** and **tailwind.json** files were empty. This made it so that writing a class like `tailwind('text-green-500')` would result in a "missing tailwind class" yellow box warning.

Here are the setup steps that worked for me:

1. Install `tailwind-rn`:
   ```bash
   yarn add tailwind-rn
   ```
2. (new) Install `postcss`
   ```bash
   yarn add --dev postcss
   ```
3. Run setup script:
   ```bash
   npx setup-tailwind-rn
   ```
   Then follow the instructions it outputs.
4. (new) Edit the **tailwind.config.js** file to be:
   ```js
   module.exports = {
     content: ['./**/*.tsx'], // should match the file paths you want tailwind to look for
     theme: {
       extend: {},
     },
     plugins: [],
     corePlugins: { transform: false, translate: false, boxShadow: false },
   };
   ```
5. Run `yarn dev:tailwind` in one terminal screen, and `expo start` in another.

If things are correct, **tailwind.css** and **tailwind.json** should have contents inside of them.

One thing I'm still noticing is that when `concurrently` watches for files to change, I also see this issue: https://github.com/vadimdemedes/tailwind-rn/issues/131

**Comment by mjrdnk** [comment]
Confirmed, it solves the problem! Thank you so much!

**Comment by vadimdemedes** [comment]
Yep, `content` must be configured in `tailwind.config.js`, so that Tailwind knows which utilities you're using and generate them in the output CSS.

**Comment by KOWLOR** [comment]
After 2 hours, and 2 clean install ... Thank you so much

**Comment by vadimdemedes** [comment]
Submitted a PR to make sure this error is gone for good → https://github.com/vadimdemedes/tailwind-rn/pull/144. See PR to learn more. Thanks @jonsamp for the solution!
