### ISSUE TITLE
Metro and the client are out of sync. Reload to reconnect.

### ISSUE THREAD

**Issue by danielmichaelni** [vadimdemedes/tailwind-rn#131]
Every once in a few saves when using a new tailwind class I get this error: `Metro and the client are out of sync. Reload to reconnect.`

If I'm using tailwind classes that I've already used (they currently exist in tailwind.css), I never get the error.

**Comment by kelvinndmo** [comment]
Am also facing this issue @vadimdemedes

**Comment by jonsamp** [comment]
I ran into this same issue. I attempted to add a custom `metro.config.js` to my project to add middleware, but I was not able to figure it out. If someone smarter than me wants to help, I think there may be a race condition where metro is watching files so that it can run HMR (fast refresh). But since some files change immediately because of `yarn dev:tailwind`, my hypothesis is that this causes metro to get out of sync.

Instead of running `yarn dev:tailwind`, I wonder if it's possible to run `yarn build:tailwind` before metro executes HMR? Just an idea.

**Comment by vadimdemedes** [comment]
I have seen this issue myself, but couldn't fix the warning. It seems that it doesn't affect the correctness of generated styles, or does it?

Any help here is appreciated!

**Comment by vadimdemedes** [comment]
This may have been fixed via https://github.com/vadimdemedes/tailwind-rn/pull/136 in the [`v4.0.1`](https://github.com/vadimdemedes/tailwind-rn/releases/tag/v4.0.1) release. Could you try it and let me know if it helped?

**Comment by jonsamp** [comment]
This solves the issue. Now, when developing, if you add a tailwind class that has not been used before, it will say that the class does not exist for a split second, before it fast refreshes again with the new style applied. This is great + a big improvement over reloading with "r". 

I think we can close this one.

**Comment by kelvinndmo** [comment]
Agree @jonsamp

**Comment by vadimdemedes** [comment]
> it will say that the class does not exist for a split second, before it fast refreshes again with the new style applied

Does the warning go away on its own or you have to manually dismiss it?

**Comment by jonsamp** [comment]
The warning only shows for a split second while it's reloading. Then it disappears after a subsequent fast refresh. Here's a video example. I'm just adding random class names and saving the file on the left (I'm not pressing "r" or anything):


https://user-images.githubusercontent.com/6455018/151680786-6141fd14-99b4-47e1-a0b6-ee3d0bba4b7c.mp4

**Comment by vadimdemedes** [comment]
Awesome, thanks for the recording!
