### ISSUE TITLE
[Proposal] create Babel plugin to avoid performance penalty as  Nozbe/Zacs does

### ISSUE THREAD

**Issue by ecreeth** [vadimdemedes/tailwind-rn#3]
My proposal in create a Babel plugin for transform our Tailwind styles to native styles to avoid performance penalty, similar as  [Nozbe/Zacs](https://github.com/Nozbe/zacs) does

### As the picture shows
![imagen](https://user-images.githubusercontent.com/20761166/76262344-6fb15180-6232-11ea-9ae4-9443e64a6b80.png)

And maybe allow to write something like this:
 ```jsx 
tailwind(`justify-center ${{ flex: 1 }} items-center px-4 bg-gray-800`)
```

**Comment by vadimdemedes** [comment]
Have you experienced any performance issues with this module? It's practically the same as just using built-in React Native styles.

**Comment by therealadum** [comment]
@vadimdemedes I don't think there is a need for a plugin, but according to https://reactnative.dev/docs/stylesheet there are performance implications of flattening your stylesheet into an object because of loss of internal IDs for pushing information across the bridge. IIRC the performance for react native specifically is negligible as of version ~0.59 - though I can't find the specific documentation for that claim.

**Comment by vadimdemedes** [comment]
You can extract styles into a `StyleSheet` just as you would without this module:

```js
StyleSheet.create({
  button: tailwind('bg-blue-200 text-blue-700')
})
```
